name: campus_mapper
description: "Campus Mapper: A Smart Campus Initative to help students navigate effectively on campus."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
  # google_maps_widget: ^1.0.6
  widget_to_marker: ^1.0.6
  shared_preferences: ^2.5.1
  provider: ^6.1.2
  google_fonts:
  # flutter_google_street_view:
  google_maps_routes: ^1.1.2
  firebase_core: ^3.11.0
  # firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_typeahead: ^5.2.0
  firebase_auth: ^5.4.2
  hugeicons: ^0.0.7
  flex_color_scheme: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/markers/
