name: campus_mapper
description: "Campus Mapper: A Smart Campus Initative to help students navigate effectively on campus."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.1
  # google_maps_widget: ^1.0.6
  widget_to_marker: ^1.0.6
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  google_fonts:
  # flutter_google_street_view:
  google_maps_routes: ^1.1.2
  # firebase_core: ^3.13.0
  # firebase_auth: ^5.4.0
  # firebase_auth: ^5.5.2
  # cloud_firestore: ^5.6.6
  # firebase_storage: ^12.4.5
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  flutter_typeahead: ^5.2.0
  hugeicons: ^0.0.10
  flex_color_scheme: ^8.2.0
  supabase_flutter: ^2.8.4
  http:

  flutter_activity_recognition: ^4.0.0
  flutter_foreground_task: ^9.1.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/markers/
