// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBci9OKE5PLGRhzSXl56DkDqR7IE8Mo3ZM',
//     appId: '1:1011362700758:web:d0b14a4de5c208f8331877',
//     messagingSenderId: '1011362700758',
//     projectId: 'campus-mapper-4e1d9',
//     authDomain: 'campus-mapper-4e1d9.firebaseapp.com',
//     storageBucket: 'campus-mapper-4e1d9.firebasestorage.app',
//     measurementId: 'G-MJXB45RPCC',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCkXP2pehtv4K6vAcJ4bcZrnYJErNRtNfs',
//     appId: '1:1011362700758:android:0384fd906ca50459331877',
//     messagingSenderId: '1011362700758',
//     projectId: 'campus-mapper-4e1d9',
//     storageBucket: 'campus-mapper-4e1d9.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBzLg4qUI9r6q8G_UAegAi65m_nnFGMX50',
//     appId: '1:1011362700758:ios:cee0b23f02b0d801331877',
//     messagingSenderId: '1011362700758',
//     projectId: 'campus-mapper-4e1d9',
//     storageBucket: 'campus-mapper-4e1d9.firebasestorage.app',
//     iosBundleId: 'com.suptle.campusMapper',
//   );

// }